#!/usr/bin/env python3
"""
Generate an HTML report from an Artillery JSON report with key metrics and simple charts.
"""
import json
import sys
from pathlib import Path

TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Stress Test Report - {title}</title>
  <style>
    body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, 'Helvetica Neue', Arial, 'Noto Sans', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; margin: 24px; color: #0f172a; }}
    h1 {{ margin-bottom: 0; }}
    .muted {{ color: #64748b; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 16px; margin: 16px 0; }}
    .card {{ border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.04); }}
    .kpi {{ font-size: 28px; font-weight: 700; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ border-bottom: 1px solid #e2e8f0; text-align: left; padding: 8px; }}
    th {{ background: #f8fafc; }}
    .pass {{ color: #16a34a; font-weight: 600; }}
    .warn {{ color: #ca8a04; font-weight: 600; }}
    .fail {{ color: #dc2626; font-weight: 600; }}
    footer {{ margin-top: 24px; color: #64748b; font-size: 13px; }}
  </style>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
</head>
<body>
  <h1>Stress Test Report</h1>
  <div class="muted">{title}</div>

  <div class="grid">
    <div class="card">
      <div class="muted">Total Requests</div>
      <div class="kpi">{total_requests}</div>
    </div>
    <div class="card">
      <div class="muted">Request Rate</div>
      <div class="kpi">{rps:.1f} req/s</div>
    </div>
    <div class="card">
      <div class="muted">Success Rate</div>
      <div class="kpi">{success_rate:.1f}%</div>
    </div>
    <div class="card">
      <div class="muted">Latency p95</div>
      <div class="kpi">{p95} ms</div>
    </div>
  </div>

  <div class="grid">
    <div class="card">
      <h3>Status Codes</h3>
      <canvas id="codesChart" height="140"></canvas>
    </div>
    <div class="card">
      <h3>Latency Percentiles</h3>
      <canvas id="latencyChart" height="140"></canvas>
    </div>
  </div>

  <div class="card">
    <h3>Per-Endpoint p95</h3>
    <table>
      <thead>
        <tr><th>Endpoint</th><th>p95 (ms)</th><th>Mean (ms)</th></tr>
      </thead>
      <tbody>
        {endpoint_rows}
      </tbody>
    </table>
  </div>

  <div class="card">
    <h3>Assessment</h3>
    <ul>
      <li>Latency p95: <span class="{latency_class}">{latency_msg}</span></li>
      <li>Success rate: <span class="{success_class}">{success_msg}</span></li>
      <li>Rate limiting: <span class="{rl_class}">{rl_msg}</span></li>
    </ul>
  </div>

  <footer>Generated by generate_html_report.py</footer>

  <script>
    const codes = {codes_labels};
    const counts = {codes_counts};
    new Chart(document.getElementById('codesChart'), {{
      type: 'bar',
      data: {{ labels: codes, datasets: [{{ label: 'Count', data: counts, backgroundColor: '#60a5fa' }}] }},
      options: {{ responsive: true, plugins: {{ legend: {{ display: false }} }} }}
    }});

    const latLabels = ['min','p50','p90','p95','p99','max'];
    const latValues = [{lat_min},{lat_p50},{lat_p90},{lat_p95},{lat_p99},{lat_max}];
    new Chart(document.getElementById('latencyChart'), {{
      type: 'line',
      data: {{ labels: latLabels, datasets: [{{ label: 'Latency (ms)', data: latValues, borderColor: '#34d399', fill: false }}] }},
      options: {{ responsive: true, plugins: {{ legend: {{ display: false }} }} }}
    }});
  </script>
</body>
</html>
"""


def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_html_report.py <artillery_report.json> <output.html>")
        sys.exit(1)

    report_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    data = json.loads(report_path.read_text())
    agg = data.get('aggregate', {})

    # Basic KPIs
    total_requests = int(agg.get('http.requests', 0))
    rps = float(agg.get('http.request_rate', 0))

    v_created = int(agg.get('vusers.created', 0))
    v_completed = int(agg.get('vusers.completed', 0))
    success_rate = (v_completed / v_created * 100) if v_created else 0.0

    rt = agg.get('http.response_time', {})
    lat_min = rt.get('min', 0)
    lat_p50 = rt.get('median', rt.get('p50', 0))
    lat_p90 = rt.get('p90', rt.get('p95', 0))
    lat_p95 = rt.get('p95', 0)
    lat_p99 = rt.get('p99', 0)
    lat_max = rt.get('max', 0)

    # Status codes
    code_items = sorted([(k.replace('http.codes.', ''), v) for k, v in agg.items() if k.startswith('http.codes.')], key=lambda x: x[0])
    codes_labels = [c for c, _ in code_items]
    codes_counts = [int(v) for _, v in code_items]

    # Per-endpoint
    endpoints = {}
    for key, val in agg.items():
        if 'plugins.metrics-by-endpoint' in key and isinstance(val, dict) and 'response_time' in key:
            parts = key.split('.')
            if len(parts) >= 3:
                ep = parts[2]
                endpoints[ep] = {**endpoints.get(ep, {}), **val}

    endpoint_rows = '\n'.join(
        f"<tr><td>{ep}</td><td>{metrics.get('p95','N/A')}</td><td>{metrics.get('mean','N/A')}</td></tr>"
        for ep, metrics in sorted(endpoints.items())
    ) or '<tr><td colspan="3" class="muted">No endpoint metrics available</td></tr>'

    # Assessment
    p95_target = 2000
    latency_class = 'pass' if lat_p95 <= p95_target else 'fail'
    latency_msg = f"p95 {lat_p95}ms (target < {p95_target}ms)"

    if success_rate >= 95:
        success_class = 'pass'
        success_msg = f"{success_rate:.1f}% >= 95%"
    elif success_rate >= 80:
        success_class = 'warn'
        success_msg = f"{success_rate:.1f}% between 80%-95%"
    else:
        success_class = 'fail'
        success_msg = f"{success_rate:.1f}% < 80%"

    rl = int(agg.get('http.codes.429', 0))
    rl_class = 'fail' if rl > 0 else 'pass'
    rl_msg = f"{rl} 429s" if rl > 0 else 'none detected'

    html = TEMPLATE.format(
        title=report_path.name,
        total_requests=total_requests,
        rps=rps,
        success_rate=success_rate,
        p95=lat_p95,
        endpoint_rows=endpoint_rows,
        latency_class=latency_class,
        latency_msg=latency_msg,
        success_class=success_class,
        success_msg=success_msg,
        rl_class=rl_class,
        rl_msg=rl_msg,
        codes_labels=json.dumps(codes_labels),
        codes_counts=json.dumps(codes_counts),
        lat_min=lat_min,
        lat_p50=lat_p50,
        lat_p90=lat_p90,
        lat_p95=lat_p95,
        lat_p99=lat_p99,
        lat_max=lat_max,
    )

    out_path.write_text(html)
    print(f"✅ HTML report written to {out_path}")


if __name__ == '__main__':
    main()
